---
name: "Paper Case 2"
dynamics:
  type: "CR3BP"
  mass_rat: 1.215058560962404e-2
  l_star: 389703
  mu1: 398600.4418
  mu2: 4902.8
hot_starter:
  bool: false
  file: 'init_conds/paper/threebody/sol.pkl'
integration:
  a_tol: &atol 1.e-12
  r_tol: 1.e-12
  int_points: 16
  mc_div: 2
segments: 41
boundary_conditions:
  t0: "2026-01-01T00:00:00"
  tf: "2026-02-01T00:00:00"
  y0: [8.3603117159904405E-1, -1.1541643155763343E-27, 1.4452688653025286E-1, 3.0851196388475223E-15, 2.5413797416891232E-1, 5.0796678933577679E-16]
  yf: [1.1799104601054238E+0, -2.5961298350180279E-27, 3.1267971476431400E-2, 3.2368872060563559E-15, -1.6127660260166954E-1, 7.6850670584967512E-15]
  type: "free"
  per1: 2.7542635366442516E+0
  per2: 3.4075088453803497E+0
  alpha:
    min: 0.0
    max: 1.0
  beta:
    min: 0.0
    max: 1.0
engine:
  m0: 200
  Isp: 3337
  T_max: .2
uncertainty:
  covariance:
    initial:
      pos_sig: 1
      vel_sig: .01
      mass_sig: 1.e-20
    target:
      pos_sig: 35
      vel_sig: .02
      mass_sig: 60
  acc_sig: 1.e-11
  gates:
    fixed_mag: 1.e-2
    prop_mag: 1.e-2
    fixed_point: 1.e-2
    prop_point: 1.e-2
  eps: .001
UT:
  alpha: 1.0
  beta: 2.0
  kappa: 4.0
SNOPT:
  major_opt_tol: 1e-5
  major_feas_tol: 1.e-6
  minor_feas_tol: 1.e-6
  major_iter_limit: 5000
  partial_price: 1
  linesearch_tol: .99
  function_prec: 1e-11
constraints:
  deterministic:
    det_col_avoid:
      bool: true
      parameters: &col_avoid
        r_obs: [384967.8803361727, 0., 0.]
        safe_d: 1737.5
  stochastic:
    det_col_avoid:
      bool: true
      parameters: *col_avoid
    stat_col_avoid:
      bool: false
      parameters: *col_avoid